### ISSUE TITLE
Can the figures used in these notebooks be reproduced with permission and citation?

### ISSUE THREAD

**Issue by rbavery** [ericmjl/dl-workshop#7]
In particular, this figure? https://github.com/ericmjl/dl-workshop/blob/master/docs/figures/infographic.pdf

As a part of my thesis' introduction section I've included a background on neural networks and CNNs, and having a figure that explains the architecture in three different ways would be helpful to the reader.

**Comment by ericmjl** [comment]
@rbavery yes, please do so! Would it help if I placed them in a location with a DOI?

**Comment by ericmjl** [comment]
OK, I just went in directly and made a DOI, if that helps you: 10.6084/m9.figshare.12424571. It's for the entire repo.

**Comment by ericmjl** [comment]
Please feel free to close whenever! :smile:

**Comment by rbavery** [comment]
Wow, thanks a bunch Eric for the quick reply and DOI link! And the awesome figures.
